#!/usr/bin/env bash
# =============================================================================
# Pathfinder Frontend Git Hooks Setup
# =============================================================================
# Run this script once after cloning the repository.
# It creates a pre-push git hook that runs all quality checks before
# allowing a push to the remote.
#
# Usage:
#   ./scripts/setup-hooks.sh
# =============================================================================

set -euo pipefail

# ---- Configuration ----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOOKS_DIR="$PROJECT_ROOT/.git/hooks"

# ---- Colors ----
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "========================================"
echo "  Pathfinder Frontend Git Hooks Setup"
echo "========================================"
echo ""

# ---- Verify we are in a git repository ----
if [ ! -d "$PROJECT_ROOT/.git" ]; then
  echo -e "${RED}ERROR: Not a git repository.${NC}"
  echo "Run this script from the project root after 'git clone'."
  exit 1
fi

# ---- Create hooks directory if it does not exist ----
if [ ! -d "$HOOKS_DIR" ]; then
  mkdir -p "$HOOKS_DIR"
  echo "Created $HOOKS_DIR"
fi

# ---- Make pre-push-check.sh executable ----
if [ ! -f "$SCRIPT_DIR/pre-push-check.sh" ]; then
  echo -e "${RED}ERROR: scripts/pre-push-check.sh not found.${NC}"
  echo "Ensure the script exists before running setup."
  exit 1
fi
chmod +x "$SCRIPT_DIR/pre-push-check.sh"
echo -e "${GREEN}[1/2]${NC} Made scripts/pre-push-check.sh executable"

# ---- Create pre-push hook ----
PRE_PUSH_HOOK="$HOOKS_DIR/pre-push"

# Back up existing hook if present
if [ -f "$PRE_PUSH_HOOK" ]; then
  cp "$PRE_PUSH_HOOK" "${PRE_PUSH_HOOK}.backup"
  echo -e "${YELLOW}NOTE:${NC} Existing pre-push hook backed up to pre-push.backup"
fi

cat > "$PRE_PUSH_HOOK" << 'HOOK_EOF'
#!/usr/bin/env bash
# =============================================================================
# Git pre-push hook — runs Pathfinder Frontend quality checks before push
# Generated by scripts/setup-hooks.sh
# =============================================================================
#
# To bypass this hook in an emergency (NOT recommended):
#   git push --no-verify
#
# To run checks manually:
#   ./scripts/pre-push-check.sh
# =============================================================================

set -euo pipefail

# Find the project root (where .git lives)
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$HOOK_DIR/../.." && pwd)"

# The pre-push-check script
CHECK_SCRIPT="$PROJECT_ROOT/scripts/pre-push-check.sh"

if [ ! -f "$CHECK_SCRIPT" ]; then
  echo "WARNING: Pre-push check script not found at $CHECK_SCRIPT"
  echo "Skipping pre-push checks. Run ./scripts/setup-hooks.sh to fix."
  exit 0
fi

if [ ! -x "$CHECK_SCRIPT" ]; then
  chmod +x "$CHECK_SCRIPT"
fi

echo ""
echo "Running pre-push quality checks..."
echo "(bypass with 'git push --no-verify' in emergencies only)"
echo ""

exec "$CHECK_SCRIPT"
HOOK_EOF

chmod +x "$PRE_PUSH_HOOK"
echo -e "${GREEN}[2/2]${NC} Created .git/hooks/pre-push"

echo ""
echo "========================================"
echo -e "  ${GREEN}Git hooks installed successfully!${NC}"
echo "========================================"
echo ""
echo "What happens now:"
echo "  - Every 'git push' will run lint, type-check, build, and CodeRabbit review"
echo "  - Push will be blocked if any check fails"
echo "  - Use 'git push --no-verify' to bypass (emergencies only)"
echo ""
echo "To test the hook manually:"
echo "  ./scripts/pre-push-check.sh"
echo ""
